Ft psychologists development
davidcurras/mindset-2021 pull request #13
Opened 2021-11-15 02:22 UTC by valeferaudo

2021-11-15 17:21 UTC, agustin-schiaffino requested changes

2021-11-15 17:21 UTC, agustin-schiaffino commented on controllers/psychologists.js
> +  newPsychologist.save((err, psychologist) => {
aca en el save y lo que viene abajo vale fijate que no lo tenes como lo tenemos yo y juli por ejemplo, y nose si no te estaria faltando el then, nose si te funciona asi como lo tenes pero por las dudas fijate como lo tenemos juli y yo

2021-11-15 17:21 UTC, agustin-schiaffino commented on controllers/psychologists.js
> +  const { id } = req.params;
aca tambien te estarian faltando el then y el catch mepa, y vi que en el remove tmb, fijate eso por las dudas, quiza te funciona igual asi pero creo que habia q hacerlo con el then y el catch

2021-11-15 19:02 UTC, valeferaudo commented on controllers/psychologists.js
> +  newPsychologist.save((err, psychologist) => {
Me funciona igual, pero lo reescribí para mantener la consistencia con el grupo! (Idem en el edit y remove)

2021-11-15 19:36 UTC, agustin-schiaffino requested changes

2021-11-15 19:36 UTC, agustin-schiaffino commented on routes/psychologists.js
> +router.post('/add', isNotEmpty, validateFormat, validateLength, psychologists.add);
vale perdon que esto nolo vi antes, aca en los metodos post put y delete, no hace falta aclarar en la ruta el add, edit y remove, deberia dejarlo asi: post(/), put(/:id), delete(/:id), no se si me explico, sino fijate en los demas como lo tenemos

2021-11-15 19:51 UTC, agustin-schiaffino approved these changes

2021-11-16 02:45 UTC, davidcurras approved these changes

2021-11-16 15:04 UTC, merged