Ft applications development
davidcurras/mindset-2021 pull request #14
Opened 2021-11-15 02:44 UTC by AlfonsoScornavacca

2021-11-15 15:50 UTC, davidcurras requested changes

2021-11-15 15:50 UTC, davidcurras commented on controllers/applications.js
> +      if (data.length === 0) return res.status(404).json({ msg: `Position not found by ID: ${idOpenPosition}` });
El mensaje en este caso deberia ser: `${notFoundTxt} PositionId:  ${idOpenPosition}`

2021-11-15 15:50 UTC, davidcurras commented on controllers/candidates.js
> +/* const fs = require('fs');
No entiendo el motivo por el cual dejás comentado todo el codigo de candidates.js

2021-11-15 15:50 UTC, davidcurras commented on models/Applications.js
> +    ref: 'Open Position',
Probaste que esto funcione? Me parece que no deberia ir el espacio entre la palabra Open y Position, pero no estoy 100% seguro

2021-11-15 15:50 UTC, davidcurras commented on package.json
> +{
No entiendo por qué te figuran cambios en todo este archivo si no cambiaste nada

2021-11-15 15:50 UTC, davidcurras commented on controllers/profile-types.js
> +const fs = require('fs');
No entiendo por qué te figuran cambios en todo este archivo si no cambiaste nada

2021-11-15 20:46 UTC, Pablo-Balbo approved these changes

2021-11-16 16:24 UTC, davidcurras approved these changes

2021-11-16 18:50 UTC, merged