Ft companies development
davidcurras/mindset-2021 pull request #18
Opened 2021-11-15 15:27 UTC by GuidoGlielmi

Pull request of ft-companies-development to development

2021-11-15 19:22 UTC, valeferaudo requested changes

2021-11-15 19:22 UTC, valeferaudo commented on controllers/companies.js
> +const idNotFoundString = 'Company not found with ID:';
Lo que hicimos algunos es poner el string= 'Company not found by ' y entonces lo podes agregar tambien el el search

2021-11-15 19:22 UTC, valeferaudo commented on controllers/companies.js
> +      if (!found) {
el if puede ir en una linea ya que solo tiene una linea

2021-11-15 19:22 UTC, valeferaudo commented on controllers/companies.js
> +      if (found.length === 0) {
Fijate lo de los if que solo tienen una línea se puede acotar, en varios lugares aparece así

2021-11-15 19:22 UTC, valeferaudo commented on validators/companies.js
> +function requiredCompanies(req, res, next) {
Acá te dejo a modo de comentario. Quizás es una mejor forma de validar los campos requeridos pero el resto del equipo no los hizo así. Deberíamos acordar con cual quedarnos, entre tu alternativa o la que usó el equipo.

2021-11-15 19:22 UTC, valeferaudo commented on validators/companies.js
> +const checkLength = (word, minLength, maxLength) => {
Ese lo podes meter directamente en el if del validateLength. Fijate en el mio o en alguno de los chicos para ver como hacerlo. David nos comentó que es innecesario hacer una funcion que solo retorne true o false despues de un if simple

2021-11-15 19:22 UTC, valeferaudo commented on validators/companies.js
> +const validateDataType = (req, res, next) => {
Acá aplica lo mismo que lo que te digo de los campos requeridos. Quizás en mejor esta validación que la nuestra, pero por consistencia de código deberíamos adoptar una para todo el equipo. Propongamos una llamada con David para charlar sobre cual es mejor y adoptamos esa como equipo.

2021-11-16 01:11 UTC, valeferaudo approved these changes

2021-11-16 16:18 UTC, davidcurras approved these changes

2021-11-16 18:21 UTC, merged