Ft profile types development
davidcurras/mindset-2021 pull request #19
Opened 2021-11-15 16:03 UTC by Pablo-Balbo

Pull request of ft-profile-types-development to development.

2021-11-15 16:20 UTC, julianv97 requested changes
Te dejo este comentario flotante, te faltó pasar a nomenclatura PascalCase el model de OpenPositions

2021-11-15 16:20 UTC, julianv97 commented on controllers/profile-types.js
> +  newProfileType.save((err, profileType) => {
deberías resolver este método save con then - catch, como acordamos en reuniones. Así queda consistente con lo que hicieron todos los otros integrantes del equipo.

2021-11-15 16:20 UTC, julianv97 commented on controllers/profile-types.js
> +      if (profileTypes.length === 0) {
este if te debería quedar en una sola línea sacandole las llaves y subiendo el return en la misma línea que el if

2021-11-15 16:40 UTC, Pablo-Balbo commented on controllers/profile-types.js
> +  newProfileType.save((err, profileType) => {
Done.

2021-11-15 16:40 UTC, Pablo-Balbo commented on controllers/profile-types.js
> +      if (profileTypes.length === 0) {
Done.

2021-11-15 16:52 UTC, julianv97 approved these changes

2021-11-16 16:22 UTC, davidcurras approved these changes

2021-11-17 02:11 UTC, merged