Ft candidates controller
davidcurras/mindset-2021 pull request #2
Opened 2021-11-08 01:07 UTC by valeferaudo

Development of getAll, getByID, getByName, add, edit and remove methods for candidates object.

2021-11-08 04:06 UTC, davidcurras requested changes

2021-11-08 04:06 UTC, davidcurras commented on controllers/candidates.js
> +    let errorMsg = [];
Las validaciónes deberías sacarlas en una función separada, y coordinarte con el resto del equipo en cómo van a manejarlas y que tipo de controles y mensajes van a usar.

2021-11-08 04:06 UTC, davidcurras commented on controllers/candidates.js
> +        res.status(404).json({
En este caso el status correcto es 400. Bad Request

2021-11-08 04:06 UTC, davidcurras commented on controllers/candidates.js
> +                candidate.firstName = req.query.firstName !== undefined ? req.query.firstName : candidate.firstName;
Esta linea se puede reducir
`candidate.firstName = req.query.firstName || candidate.firstName;`
Hace los mismo con las demás

2021-11-08 04:06 UTC, davidcurras commented on controllers/candidates.js
> +            else{
Tanto el if como el else hacen return candidate. No es necesario hacer un else y podes borrar el return al final del if, moviendolo afuera del if para que sea algo que pasa siempre al final, entre o no entre.

2021-11-08 04:06 UTC, davidcurras commented on data/candidates.json
> +{"list":[{"id":1,"firstName":"Roberto","lastName":"Amthor","email":"gamthor0@amazon.co.jp","password":"r1BPl0XTu","pictureUrl":"http://dummyimage.com/133x100.png/cc0000/ffffff","phone":"616-508-0843"
Esta lista claramente es la que te quedó luego de meter mano probando el server. Deberias volver a descargar el archivo Mockaroo como aclaré anoche en los mensajes.

2021-11-08 17:19 UTC, agustin-schiaffino requested changes

2021-11-08 17:19 UTC, agustin-schiaffino commented on controllers/candidates.js
> +            message:'Candidate not found by ID'
creo que el mensaje podrias ponerlo en una sola linea como hizo juli, y ademas estaria bueno que uses los template strings como habiamos dicho para poder incluir el id, fijate como lo tiene juli

2021-11-08 17:19 UTC, agustin-schiaffino commented on controllers/candidates.js
> +    else{
creo que el else se puede prescindir en este caso que se pregunta por la negativa

2021-11-08 17:19 UTC, agustin-schiaffino commented on controllers/candidates.js
> +        res.status(404).json({
aca te marco lo mismo que en lo anterior, faltaria un return antes del res.status y tratar de usar el template string en el mensaje, y lo mismo con lo del else, fijate si tenes que corregirlo mas abajo eso asi no hago muchos comentarios iguales, y siempre guiate con el controller de juli, al menos asi lo hice yo

2021-11-08 17:19 UTC, agustin-schiaffino commented on controllers/candidates.js
> +    const updatedCandidate = {};
esta constante aca no entiendo muy bien porque la creaste, en eso quiza david pueda ayudarte mejor, pero bueno dado que no lo vi en el de juli te lo marco por las dudas

2021-11-08 17:19 UTC, agustin-schiaffino commented on controllers/candidates.js
> +        })
al final de esta linea faltaria el ;

2021-11-08 17:19 UTC, agustin-schiaffino commented on controllers/candidates.js
> +    const foundCandidates = candidates.list.filter(candidate => candidate.firstName.toLowerCase() === req.params.name.toLowerCase())
fijate aca y compara con el getById, en uno creaste una constante con el req.query.id y en esta directamente lo escribiste sin hacer la const, trata de elegir una forma para hacerlo igual en todas, julio creo la constante siempre, yo en mi caso decidi hacerlo manual, creo que ambas formas estan bien pero deberias seguir una de las dos

2021-11-08 17:19 UTC, agustin-schiaffino commented on controllers/candidates.js
> +                })
aca denuevo faltaria el ; al final, fiajte de revisarlo en todo el archivo siguiendo el ejemplo de juli

2021-11-08 18:23 UTC, valeferaudo commented on controllers/candidates.js
> +    const updatedCandidate = {};
Acá me confundí, y era let.. Lo hice para retornar el objeto que se modifica.

2021-11-09 01:10 UTC, agustin-schiaffino requested changes

2021-11-09 01:10 UTC, agustin-schiaffino commented on controllers/candidates.js
> +    }
aca iria un ; al final a mi parecer

2021-11-09 01:10 UTC, agustin-schiaffino commented on controllers/candidates.js
> +    else{
este else aca no hace falta dado que pregutnas por la negativa

2021-11-09 01:10 UTC, agustin-schiaffino commented on controllers/candidates.js
> +        if(err){
aca dentro del if del err, deberia hacer un return para que te pare la funcion en caso de que capture el error, nose si lo aclare esto en la anterior review, si no lo hice perdon jajaj, trata de agregar este return a todos los if de los write file

2021-11-09 01:10 UTC, agustin-schiaffino commented on controllers/candidates.js
> +            })
aca tambien faltaria el ; fijate que haya ; en todos los res.status o res.json

2021-11-09 02:30 UTC, agustin-schiaffino approved these changes

2021-11-09 15:16 UTC, davidcurras approved these changes

2021-11-09 15:16 UTC, merged