Ft psychologists controller
davidcurras/mindset-2021 pull request #3
Opened 2021-11-08 01:18 UTC by GuidoGlielmi

Merge de ft-psychologists-controller a development

2021-11-08 04:21 UTC, davidcurras requested changes

2021-11-08 04:21 UTC, davidcurras commented on controllers/psychologists.js
> +const calculateLarger = (collection) => {
Deberías renombrar esta función para que se llame getLastId. Es mucho más claro que calculateLarger

2021-11-08 04:21 UTC, davidcurras commented on controllers/psychologists.js
> +  if (found)
Una buena forma de ahorrarse un par de lineas de código y dejar los casos alternativos al principio de la función para que todos vean la excepción, es preguntar por la condición negada y retornar si pasa esto. Es decir, en lugar de hacer el else en la linea 37, reemplazarías el if en la 30 por `if (!found) return res.status(404).json([])` y después no necesitas decir else, dado que si entra en el if ya retorna, y si no entra sigue normal por el caso de éxito.

2021-11-08 04:21 UTC, davidcurras commented on controllers/psychologists.js
> +  if (req.body.first_name) newPsychologist.first_name = req.body.first_name;
Esta linea se puede reducir:
`newPsychologist.first_name = req.body.first_name || null`

2021-11-08 04:21 UTC, davidcurras commented on data/psychologists.json
> +    "first_name": "Nettie",
Los nombres de variables y propiedades deben ser camelCase, es decir que por ejemplo deberías cambiar first_name por firstName

2021-11-08 04:21 UTC, davidcurras commented on controllers/psychologists.js
> +  fs.writeFile(path.join(__dirname, '../data/psychologists.json'), JSON.stringify(psyList), (err) => {
Usaste Path.Join para generar la ruta. Me parece una buena práctica y es más seguro que poner el string directo, pero el resto del equipo no lo usó, deberías ponerte de acuerdo con el equipo. O lo usan siempre o nunca.

2021-11-08 04:21 UTC, davidcurras commented on controllers/psychologists.js
> +  res.status(200).send(newPsychologist);
No es necesario aclarar el status 200 porque por defecto .send y .json ya envian 200. Y te recomiendo usar .json para evitar problemas

2021-11-08 04:21 UTC, davidcurras commented on controllers/psychologists.js
> +    psyList = psyList.map((psy) => {
Ponete de acuerdo con el equipo en cómo van a manejar las validaciónes. Cada uno hizo lo que le pareció.

2021-11-08 04:21 UTC, davidcurras commented on controllers/psychologists.js
> +  let foundPsyIndex = psyList.findIndex((psy) => psy.id === parseInt(req.params.id));
No tiene mucho sentido hacer todo esto de findIndex si podés resolverlo con un simple filter. Fijate como lo hizo Julian.

2021-11-08 04:21 UTC, davidcurras commented on controllers/psychologists.js
> +const removeWithAnyParam = (req, res) => {
No me queda muy claro el motivo por el que quisieras eliminar un candidato pasando cualquier parametro. Entiendo que como ejercicio está bueno, pero la funcionalidad de eliminar es muy sensible y generalmente se hace por id para asegurarse que se está eliminando al correcto y evitar eliminar por error. No tengo problema si la queres dejar pero esta fuera del alcance del curso y creo que no deberiamos exportala ni usarla. Te diría que dejes el código comentado para que quede constancia del trabajo y te sirva como ejemplo pero en un proyecto real el lider te pediria que lo elimines directamente.

2021-11-08 04:21 UTC, davidcurras commented on index.js
> +const psychologists = require('./controllers/psychologists');
Agregaste psicologos y eliminaste candidatos. Deberias dejar ambos.

2021-11-08 14:48 UTC, valeferaudo commented on controllers/psychologists.js
> +  if (!foundPsy) return res.status(404).send({ message: `Psychologist not found with id: ${req.params.id}` });
Mantener como Julian. res.status().json()

2021-11-08 14:57 UTC, valeferaudo requested changes

2021-11-08 14:57 UTC, valeferaudo commented on controllers/psychologists.js
> +  if (!foundPsy) return res.status(404).send({ message: `Psychologist not found with id: ${req.params.id}` });
Mantener como Julian. res.status().json()

2021-11-08 15:06 UTC, valeferaudo requested changes

2021-11-08 15:06 UTC, valeferaudo commented on controllers/psychologists.js
> +const add = (req, res) => {
Acá usas req.body, mientras que el equipo creo que utiliza req.query. No esta mal tu código pero no es consistente con el equipo.

2021-11-09 02:25 UTC, valeferaudo requested changes

2021-11-09 02:25 UTC, valeferaudo commented on controllers/psychologists.js
> +    return res
Solo por cuestión estetica y de lectura, tendriamos que ver con David como conviene escribir la res.status.json. Y fijate de mantenerte consistente en todo el código.

2021-11-09 02:25 UTC, valeferaudo commented on controllers/psychologists.js
> +  fs.writeFile(
Aca aplica lo mismo que te digo arriba, no se que es mejor con respecto a facilidad de lectura. Agrego este comentario mas que nada para acordarse de consultar a David.

2021-11-09 02:25 UTC, valeferaudo commented on controllers/psychologists.js
> +      psy.turns = req.query.turns || [];
Acá si viene algo en req.query.turns lo asigna como string creo, y no como array.

2021-11-09 15:24 UTC, davidcurras approved these changes

2021-11-09 17:32 UTC, valeferaudo approved these changes

2021-11-09 18:20 UTC, merged