Ft profile types controller
davidcurras/mindset-2021 pull request #4
Opened 2021-11-08 01:28 UTC by AlfonsoScornavacca

Week 08 problematic solved, I need to create a function to find bigger id.

2021-11-08 04:33 UTC, davidcurras requested changes

2021-11-08 04:33 UTC, davidcurras commented on controllers/candidates.js
> +    console.log('prueba');
Esto no debería estar en el commit dado que no es parte de tu recurso.

2021-11-08 04:33 UTC, davidcurras commented on controllers/profile-types.js
> +const calculateLarger = (collection) => {
Deberías renombrar esta función para que se llame getLastId. Es mucho más claro que calculateLarger

2021-11-08 04:33 UTC, davidcurras commented on controllers/profile-types.js
> +    if (profileTypesId) {
Una buena forma de ahorrarse un par de lineas de código y dejar los casos alternativos al principio de la función para que todos vean la excepción, es preguntar por la condición negada y retornar si pasa esto. Es decir, en lugar de hacer el else en la linea 26, reemplazarías el if en la 23 por `if (!profileTypesId) return res.status(404).json(...)` y después no necesitas decir else, dado que si entra en el if ya retorna, y si no entra sigue normal por el caso de éxito.

2021-11-08 04:33 UTC, davidcurras commented on controllers/profile-types.js
> +    const profileTypesName  = profileTypes.find((profileTypesName) => profileTypesName.name === (req.params.name));
getByName devuelve un array de matches, por lo que deberias usar filter en lugar de find.

2021-11-08 04:33 UTC, davidcurras commented on controllers/profile-types.js
> +  }
Ojo con la prolijidad y la consistencia de código. Tenes inconsistencias de indentación, puntos y comas, etc.

2021-11-08 04:33 UTC, davidcurras commented on controllers/profile-types.js
> +        if(error){res.status(500)}
Ponete de acuerdo con el equipo en como van a formatear los mensajes de error que van a enviar. Los demas no lo manejaron exactamente así.

2021-11-08 04:33 UTC, davidcurras commented on controllers/profile-types.js
> +          return profile;
No tiene sentido hacer un return al final de un if, si lo primero que pasa despues del if es tambien un return con exactamente lo mismo. Podes eliminar esta linea y dejar las que siguen y el resultado es el mismo.

2021-11-08 04:33 UTC, davidcurras commented on controllers/profile-types.js
> +};
Tenés muchas inconsistencias y desprolijidad en el código, se me hace dificil corregirte errores. Asegurate de revisar todo a mano cuando hagas los cambios.

2021-11-08 04:33 UTC, davidcurras commented on index.js
> +  let html = "<h1>MindeSet</h1>";
Borraste la parte de candidates y pusiste algunos casos con comillas dobles.
Deberias dejar lo de Candidates y ademas agregar tu parte. Y por favor tener cuidado y atención con la consistencia de código.

2021-11-08 22:02 UTC, AlfonsoScornavacca commented on controllers/candidates.js
> +    console.log('prueba');
Si, en realidad lo puse cuando intentábamos arreglar lo del localhost con los chicos y pensamos que me pedía un commit si o si

2021-11-09 02:01 UTC, Pablo-Balbo requested changes

2021-11-09 02:18 UTC, Pablo-Balbo requested changes

2021-11-09 02:18 UTC, Pablo-Balbo commented on controllers/profile-types.js
> +      return res.status(400).json({ message: 'Missing parameters' })};
put the last "};" below to maintain code consistency.

2021-11-09 02:18 UTC, Pablo-Balbo commented on controllers/profile-types.js
> +        return;
This return can go on the line above, before res.status ...
Same on edit function

2021-11-09 02:18 UTC, Pablo-Balbo commented on index.js
> +  html += '      <li><a href="/profile-types/:id">getById</a></li>';
Add example parameters to paths for error prevent.

2021-11-09 02:38 UTC, Pablo-Balbo approved these changes

2021-11-09 15:25 UTC, davidcurras approved these changes

2021-11-09 21:54 UTC, merged