Ft administrators controller
davidcurras/mindset-2021 pull request #5
Opened 2021-11-08 01:30 UTC by agustin-schiaffino

Development of getAll, getByID, getByName, add, edit and remove methods for administrators object.

2021-11-08 04:30 UTC, sofpag commented on controllers/administrators.js
> +        res.json(adminData.filter(administrator => administrator.id === parseInt(req.params.id)))
; al final... creo

2021-11-08 04:44 UTC, sofpag reviewed
Agus, con mis conocimientos solo puede marcar errores de consistencia, creo que faltaron algunas ; al final de algunas lineas 
hay una palabra mal escrita y algunas lineas vacias dentro de las funciones
y bueno, algunos errores de consistencia con el uso de las comidas dobles, simples y las templete string (` `)

2021-11-08 04:44 UTC, sofpag commented on controllers/administrators.js
> +        res.status(404).json({ msg: `No administrator with the id of ${req.params.id} founded` })
; al final... creo 
usas templetes strings pero no concatenas nada, van comillas simples

2021-11-08 04:44 UTC, sofpag commented on controllers/administrators.js
> +        res.json(adminData.filter(administrator => administrator.firstName === (req.params.name)))
; al final... creo

2021-11-08 04:44 UTC, sofpag commented on controllers/administrators.js
> +        res.status(404).json({ msg: `No administrator with the first name of ${req.params.name} founded` })
; al final... creo
usas templetes strings pero no concatenas nada, van comillas simples

2021-11-08 04:44 UTC, sofpag commented on controllers/administrators.js
> +                res.status(500).json({ msg: "Error adding administrator" })
; al final... creo 
usas " en vez de '

2021-11-08 04:44 UTC, sofpag commented on controllers/administrators.js
> +        res.json({ msg: "Administrator succesfully added", newAdmin })
; al final... creo 
usas " en vez de '
escribir: successfully

2021-11-08 04:44 UTC, sofpag commented on controllers/administrators.js
> +        res.status(400).json({ msg: "Some parameters are missing" })
; al final... creo 
usas " en vez de '

2021-11-08 04:44 UTC, sofpag commented on controllers/administrators.js
> +                res.json({ msg: "Administrator updated", administrator })
; al final... creo 
usas " en vez de '

2021-11-08 04:44 UTC, sofpag commented on controllers/administrators.js
> +        res.status(404).json({ msg: `No administrator with the id of ${req.params.id} founded` })
; al final... creo

2021-11-08 04:44 UTC, sofpag commented on controllers/administrators.js
> +        adminData = adminData.filter((administrator) => administrator.id !== parseInt(req.params.id))
; al final... creo

2021-11-08 04:44 UTC, sofpag commented on controllers/administrators.js
> +        res.status(404).json({ msg: `No administrator with the id of ${req.params.id} founded` })
; al final... creo

2021-11-08 04:44 UTC, sofpag commented on controllers/administrators.js
> +        fs.writeFile("./data/administrators.json", JSON.stringify(adminData), err => {
usas " en vez de '

2021-11-08 04:44 UTC, sofpag commented on controllers/administrators.js
> +                      res.status(500).json({ message: "Error editing administrator" });
usas " en vez de '

2021-11-08 04:44 UTC, sofpag commented on controllers/administrators.js
> +              res.status(500).json({ msg: "Error removing administrator" });
usas " en vez de '

2021-11-08 04:44 UTC, sofpag commented on controllers/administrators.js
> +        res.json({ msg: "Administrator removed" });
usas " en vez de '

2021-11-08 04:44 UTC, sofpag commented on controllers/administrators.js
> +
linea vacía

2021-11-08 04:44 UTC, sofpag commented on controllers/administrators.js
> +
linea vacía

2021-11-08 04:44 UTC, sofpag commented on controllers/administrators.js
> +
linea vacia

2021-11-08 04:44 UTC, sofpag commented on controllers/administrators.js
> +
linea vacia

2021-11-08 04:44 UTC, sofpag commented on controllers/administrators.js
> +
linea vacia

2021-11-08 05:04 UTC, davidcurras requested changes

2021-11-08 05:04 UTC, davidcurras commented on controllers/administrators.js
> +    if (validate(newAdmin)) {
Una buena forma de ahorrarse un par de lineas de código y dejar los casos alternativos al principio de la función para que todos vean la excepción, es preguntar por la condición negada y retornar si pasa esto. Es decir, en lugar de hacer el else en la linea 63, reemplazarías el if en la 55 por `if (!validate(newAdmin)) return res.status(400).json(...)` y después no necesitas decir else, dado que si entra en el if ya retorna, y si no entra sigue normal por el caso de éxito.

2021-11-08 05:04 UTC, davidcurras commented on controllers/administrators.js
> +        adminData = adminData.map(administrator => {
No deberias usar un map si no le vas a dar ningun uso a la variable `adminData` generada. Tampoco es necesario la validacion extra que hiciste con .some.
Te recomiendo revisar el código de la branch de Julian para ver como maneja el edit tambien.

2021-11-08 05:04 UTC, davidcurras commented on index.js
> +app.get('/', (req, res) => {
No es la idea que comentes los candidates, dado que este archivo lo va a utilizar todo el grupo. Sería bueno que agregues los endpoints de Administrator junto con los de candidates que habia, y elijas ejemplos concretos en las urls de href.

2021-11-09 00:33 UTC, sofpag commented on controllers/administrators.js
> +        isActive: req.query.isActive,
isActive, ... la , (coma) no va

2021-11-09 00:33 UTC, sofpag commented on controllers/administrators.js
> +            administrator.firstName = req.query.firstName || administrator.firstName;
hay algo raro en la indentación (acá es notorio, pero se repite en este archivo como en index.js), fijate el uso tab en vez de espacios (de acuerdo a las preferencias de RadiumR)
De todas formas es consistente, solo que no responde a lo acordado previamente por el grupo

2021-11-09 00:33 UTC, sofpag commented on controllers/administrators.js
> +};
me marca un error (Github) de que deberías tener una linea en blanco al final de cada archivo, en los 3 archivos Agus

2021-11-09 00:33 UTC, sofpag commented on index.js
acá dejas 2 lineas en blanco

2021-11-09 00:47 UTC, agustin-schiaffino commented on controllers/administrators.js
> +            administrator.firstName = req.query.firstName || administrator.firstName;
sofi entiendo esto que decis, pero recien viendo con el equipo como tenian configurado el visual lo tenian igual que yo con 4 spaces, por ahora no lo corregi, de ultima dsp si david me lo marca lo corrijo :)

2021-11-09 00:58 UTC, sofpag commented on controllers/administrators.js
> +            administrator.firstName = req.query.firstName || administrator.firstName;
Me parece bien Agus, de todas formas es consistente

2021-11-09 01:04 UTC, sofpag approved these changes

2021-11-09 15:27 UTC, davidcurras approved these changes

2021-11-09 17:46 UTC, merged