Ft open positions controller
davidcurras/mindset-2021 pull request #6
Opened 2021-11-08 03:13 UTC by Pablo-Balbo

Development of getAll, getByID, getByIdCompany, add, edit and remove methods for candidates object.

2021-11-08 03:52 UTC, julianv97 requested changes
controllers/open-position.js
	-Declarar como const getBiggerId para consistencia con las demás arrow functions.
	-En la función add, la condición del if en la linea 25, reemplazarla por la función validate() que acordamos
	 en el grupo para verificar que se pasen todos los datos.
	-Modificar el mensaje de error de la linea 31 por: res.status(500).json({ message: 'Error trying to save new data'});
	para que devuelva un error 500.
	-Modificar el mensaje de error de la linea 26 por: res.status(400).json({ message: 'Missing parameters' }););
	para que devuelva un error 400

index.js
	-Agregar todos los endpoints con algún dato de ejemplo como en el index de la rama de development en la variable html y luego mandarla en el res.send() de la linea 17

2021-11-08 05:13 UTC, davidcurras requested changes

2021-11-08 05:13 UTC, davidcurras commented on controllers/open-positions.js
> +let getBiggerId = (openPositions) => {
Deberías renombrar esta función para que se llame getLastId. Es mucho más claro que getBiggerId

2021-11-08 05:13 UTC, davidcurras commented on controllers/open-positions.js
> +const add = (req, res) => {
Sería bueno que tengas todos los get primero y despues el add, edit y remove siguiendo el orden que todos los demas usaron

2021-11-08 05:13 UTC, davidcurras commented on controllers/open-positions.js
> +        res.send(400)
Coordina con tus compañeros la forma de enviar mensajes de error porque varios hicieron algo diferente

2021-11-08 05:13 UTC, davidcurras commented on controllers/open-positions.js
> +    fs.writeFile('./data/open-positions.json', JSON.stringify(openPositions), err => {
Los Write File deberían ser iguales como equipo. Cada uno lo manejó ligeramente diferente. Coordina con tus compañeros y modifiquenlo.

2021-11-08 05:13 UTC, davidcurras commented on controllers/open-positions.js
> +    res.json(newOpenPosition);
Estas enviando una respuesta sin tener en cuenta lo que pasa con writeFile. Esto deberia ser ir dentro del callback de writeFile como else en caso que no haya error.

2021-11-08 05:13 UTC, davidcurras commented on controllers/open-positions.js
> +    if (openPosition) {
Una buena forma de ahorrarse un par de lineas de código y dejar los casos alternativos al principio de la función para que todos vean la excepción, es preguntar por la condición negada y retornar si pasa esto. Es decir, en lugar de hacer el else en la linea 45, reemplazarías el if en la 43 por `if (!openPosition) return res.status(404).json(...)` y después no necesitas decir else, dado que si entra en el if ya retorna, y si no entra sigue normal por el caso de éxito.

2021-11-08 05:13 UTC, davidcurras commented on controllers/open-positions.js
> +                openPosition.idCompany = req.query.idCompany ? req.query.idCompany : openPosition.idCompany;
Estas lineas se pueden reducir:
openPosition.idCompany = req.query.idCompany || openPosition.idCompany;

2021-11-08 05:13 UTC, davidcurras commented on index.js
> +    html += '  <li>Open Positions:';
No era la idea que reemplaces lo de candidates sino que agregues open position con todos los endpoints.

2021-11-08 14:20 UTC, Pablo-Balbo commented on controllers/open-positions.js
> +let getBiggerId = (openPositions) => {
Done.

2021-11-08 14:20 UTC, Pablo-Balbo commented on controllers/open-positions.js
> +const add = (req, res) => {
Done.

2021-11-08 14:20 UTC, Pablo-Balbo commented on controllers/open-positions.js
> +    fs.writeFile('./data/open-positions.json', JSON.stringify(openPositions), err => {
Done.

2021-11-08 14:23 UTC, Pablo-Balbo commented on controllers/open-positions.js
> +    if (openPosition) {
Done.

2021-11-08 14:29 UTC, Pablo-Balbo commented on index.js
> +    html += '  <li>Open Positions:';
Please, check my correction and tell me if its ok.

2021-11-08 16:28 UTC, julianv97 requested changes

2021-11-08 16:28 UTC, julianv97 commented on controllers/open-positions.js
> +const getById = (req, res) => {
Esta función no está mandando la respuesta en caso de éxito, deberías hacer un res.json(openPosition) luego del if.

2021-11-08 16:28 UTC, julianv97 commented on controllers/open-positions.js
> +    if (openPosition) {
Seguir la misma lógica de negar la condición de if para ahorrarse la sentencia del else. Esto se repite en otros if más abajo

2021-11-08 16:28 UTC, julianv97 commented on controllers/open-positions.js
> +        res.send(400)
Revisar la función validate para validar que todos los campos tengan algo a la hora de agregar.

2021-11-08 16:28 UTC, julianv97 commented on index.js
> +app.get('/open-positions/edit/:id', openPositions.edit);
Poner como endpoint un ejemplo concreto en el path. Por ejemplo '/open-positions/1' así cuando tocas el link te devuelve algo que no sea un error.

2021-11-08 16:28 UTC, julianv97 commented on index.js
> +    html += '  <li>Open Positions:';
Falta en el res.send() mandar la variable html, sería res.send(html). Además deberías agregar todas las sentencias correspondientes a candidates que ya estaban antes y no reemplazar open postions con candidates. Tienen que estar las dos.

2021-11-08 18:38 UTC, Pablo-Balbo commented on controllers/open-positions.js
> +        res.send(400)
Done.

2021-11-08 18:44 UTC, Pablo-Balbo commented on controllers/open-positions.js
> +    res.json(newOpenPosition);
Done.

2021-11-08 19:44 UTC, Pablo-Balbo commented on controllers/open-positions.js
> +                openPosition.idCompany = req.query.idCompany ? req.query.idCompany : openPosition.idCompany;
Done.

2021-11-08 19:57 UTC, Pablo-Balbo commented on controllers/open-positions.js
> +const getById = (req, res) => {
Did you mean, add else { res.json(openPosition); } right?
If it's ok, i have corrected.

2021-11-08 21:35 UTC, julianv97 commented on controllers/open-positions.js
> +const getById = (req, res) => {
You dont need the else, if you return the error in the if sentence and then continue with res.json(openPosition);

2021-11-08 21:54 UTC, Pablo-Balbo commented on controllers/open-positions.js
> +    if (openPosition) {
Done.

2021-11-09 00:26 UTC, Pablo-Balbo commented on index.js
> +    html += '  <li>Open Positions:';
I think it's done... Please Check it when you can!

2021-11-09 00:27 UTC, Pablo-Balbo commented on controllers/open-positions.js
> +const getById = (req, res) => {
Ok! Thanks! 
That's done!

2021-11-09 00:32 UTC, Pablo-Balbo commented on index.js
> +app.get('/open-positions/edit/:id', openPositions.edit);
Done.

2021-11-09 00:54 UTC, julianv97 approved these changes
Good job! Now we have to wait for David's correction

2021-11-09 15:27 UTC, davidcurras approved these changes

2021-11-10 04:45 UTC, merged