Ft interviews controller
davidcurras/mindset-2021 pull request #7
Opened 2021-11-08 04:24 UTC by sofpag

Development of getAll, getByID, getByIdCompany, add, edit and remove methods for interviews object.

2021-11-08 05:22 UTC, davidcurras requested changes

2021-11-08 05:22 UTC, davidcurras commented on controllers/interviews.js
> +const getLastId = (collection) => {  // Julián fn
Tanto en la forma de manejar getLastId como valida, tenemos que ponernos de acuerdo como equipo la forma de manejarlo. Cuando lo tengan decidido lo editamos y apruebo los cambios.

2021-11-08 05:22 UTC, davidcurras commented on controllers/interviews.js
> +// try:  http://localhost:8000/interviews
Cuando haces comentarios de funciones se acostumbra a escribirlos en la linea antes de la funcion. Es decir deberías mover este comentario a la linea 26.

2021-11-08 05:22 UTC, davidcurras commented on controllers/interviews.js
> +    const findInterviewsId = interviews.some(interviews => interviews.id === parseInt(req.params.id));
No es necesario que valides con Some, dado que find o filter ya hacen el trabajo de validar por si mismos. Sino estas validando dos veces.

2021-11-08 05:22 UTC, davidcurras commented on controllers/interviews.js
> +        res.json(interviews.filter(interviews => interviews.id === parseInt(req.params.id)));
Dado que los ids son unicos (o deberian serlo) tenes que usar .dinf en lugar de .filter en esta funcion

2021-11-08 05:22 UTC, davidcurras commented on controllers/interviews.js
> +            res.send(500).json({ msg: 'Error adding new interview' });
Ojo que acá hay un error de indentación

2021-11-08 05:22 UTC, davidcurras commented on controllers/interviews.js
> +    res.json({ msg: 'New interview successfully added', newInterviews });
Estas enviando una respuesta sin tener en cuenta lo que pasa con writeFile. Esto deberia ser ir dentro del callback de writeFile como else en caso que no haya error.

2021-11-08 05:22 UTC, davidcurras commented on controllers/interviews.js
> +    if (validate(interviews)) {
Una buena forma de ahorrarse un par de lineas de código y dejar los casos alternativos al principio de la función para que todos vean la excepción, es preguntar por la condición negada y retornar si pasa esto. Es decir, en lugar de hacer el else en la linea 68, reemplazarías el if en la 60 por if (!validate) return res.status(400).json(...) y después no necesitas decir else, dado que si entra en el if ya retorna, y si no entra sigue normal por el caso de éxito.

2021-11-08 05:22 UTC, davidcurras commented on controllers/interviews.js
> +                interviews.idCompany = editInterviews.idCompany ? editInterviews.idCompany : interviews.idCompany;
Estas lineas se pueden reducir:

`interviews.idCompany = editInterviews.idCompany || interviews.idCompany;`

2021-11-08 05:22 UTC, davidcurras commented on index.js
> +    html += '      <li><a href="/interviews">getAll</a></li>';
Ojo que las url de los href deberían corresponder a las rutas especificas de cada método. Fijate como lo hizo Julian.

2021-11-08 05:22 UTC, davidcurras commented on index.js
> +app.get('/interviews/byIdCompany/:idCompany', interviews.getByIdCompany);    // change it from getByName
Lo llamaría byCompany, dado que las busquedas de este tipo siempre se sobreentiende que es por id.

2021-11-08 13:28 UTC, AndresCespedes23 requested changes
Hola Sofi, lo tuyo creo que está muy bien, veremos que aporta David. Los datos de nuestros recursos son muy parecidos

2021-11-08 13:28 UTC, AndresCespedes23 commented on controllers/interviews.js
> +    const findId = interviews.dinf(interviews => interviews.id === parseInt(req.params.id));
Hola Sofi, fijate que no esta bien escrito el método find()

2021-11-09 02:26 UTC, AndresCespedes23 requested changes

2021-11-09 02:26 UTC, AndresCespedes23 commented on controllers/interviews.js
> +            console.log(err);
En las funciones add, edit y remove hay console.log() que no son necesarios que esten

2021-11-09 02:26 UTC, AndresCespedes23 commented on index.js
> +  html += '      <li><a href="/interviews/eddit/130">edit</a></li>';
En la ruta le esta sobrando una "d" al edit

2021-11-09 02:26 UTC, AndresCespedes23 commented on index.js
> +app.get('/interviews/byCompany/:idCompany', interviews.getByCompany);    // change it from getByName
Despues del /byCompany, podes dejar solo el ":id"

2021-11-09 02:41 UTC, sofpag commented on controllers/interviews.js
> +            console.log(err);
Si lo sé, pero de los pedazos que escuché de la reunión de la mañana de hoy entendí que el codigo de todos tiene que ser como si fuera de mismo desarrollador. Así que volví a la función de Julián y él los tiene, pero coincido

2021-11-09 02:42 UTC, sofpag commented on index.js
> +  html += '      <li><a href="/interviews/eddit/130">edit</a></li>';
Gracias!

2021-11-09 14:53 UTC, AndresCespedes23 approved these changes

2021-11-09 15:26 UTC, davidcurras approved these changes

2021-11-10 01:10 UTC, merged