Ft applications controller
davidcurras/mindset-2021 pull request #8
Opened 2021-11-08 04:29 UTC by PabloMBernal

Development of getAll, getByID, getByIdPos, getByIdCan, add, edit and remove methods for applications object.

2021-11-08 05:47 UTC, davidcurras requested changes

2021-11-08 05:47 UTC, davidcurras commented on controllers/applications.js
> +const calculateLarger = (collection) => {
Deberías renombrar esta función para que se llame getLastId. Es mucho más claro que calculateLarger

2021-11-08 05:47 UTC, davidcurras commented on controllers/applications.js
> +const validate = (object) => {
Por favor, revisa con el grupo como van a manejar las validaciones porque cada uno lo hizo diferente.

2021-11-08 05:47 UTC, davidcurras commented on controllers/applications.js
> +        res.json(empty);
Si no hay nada deberias devolver un array vacio.

2021-11-08 05:47 UTC, davidcurras commented on controllers/applications.js
> +    if (application === undefined) {
Una buena forma de ahorrarse un par de lineas de código y dejar los casos alternativos al principio de la función para que todos vean la excepción, es preguntar por la condición negada y retornar si pasa esto. Es decir, en lugar de hacer el else en la linea 41, reemplazarías el if en la 38 por `if (!application) return res.status(404).json(...)` y después no necesitas decir else, dado que si entra en el if ya retorna, y si no entra sigue normal por el caso de éxito.

2021-11-08 05:47 UTC, davidcurras commented on controllers/applications.js
> +const getByIdPos = (req, res) => {
Le cambiaría el nombre a getByPosition dado que se sobreentiende que vas a buscar la position por id.

2021-11-08 05:47 UTC, davidcurras commented on controllers/applications.js
> +const getByIdCan = (req, res) => {
Le cambiaría el nombre a getByCandidate dado que se sobreentiende que vas a buscar el candidate por id.

2021-11-08 05:47 UTC, davidcurras commented on controllers/applications.js
> +        let newItem = {
Ojo la indentación y revisa con el equipo como van a manejar las validaciónes

2021-11-08 05:47 UTC, davidcurras commented on controllers/applications.js
> +        fs.writeFile(path.join(__dirname, '../data/applications.json'), JSON.stringify(applications), error => {
Los Write File deberían ser iguales como equipo. Cada uno lo manejó ligeramente diferente. Coordina con tus compañeros y modifiquenlo.

2021-11-08 05:47 UTC, davidcurras commented on controllers/applications.js
> +        res.json(newItem);
Estas enviando una respuesta sin tener en cuenta lo que pasa con writeFile. Esto deberia ser ir dentro del callback de writeFile como else en caso que no haya error.

2021-11-08 05:47 UTC, davidcurras commented on controllers/applications.js
> +                    req.query.idCandidate === undefined ? editObj.idCandidate = editObj.idCandidate : editObj.idCandidate = parseInt(req.query.idCandidate);
Estas lineas se pueden reducir:

`editObj.idCandidate = editObj.idCandidate || parseInt(req.query.idCandidate)`

2021-11-08 05:47 UTC, davidcurras commented on index.js
> +    html += '  <li>applications:';
No era la idea que reemplaces candidates sino que agregues lo de applications.

2021-11-08 05:47 UTC, davidcurras commented on package.json
> +  },
No me queda claro por qué agregaste keywords al package json

2021-11-08 13:55 UTC, PabloMBernal commented on package.json
> +  },
esto se genero solo cuando inicialice el package, si no me decias no me daba cuenta jaja

2021-11-08 18:16 UTC, AlfonsoScornavacca commented on controllers/applications.js
> -            if (error) { res.status(500) }
Falta mensaje de error y el ;

2021-11-08 18:28 UTC, AlfonsoScornavacca requested changes

2021-11-08 18:28 UTC, AlfonsoScornavacca commented on controllers/applications.js
> -                if (error) { res.status(500) }
falta mensaje de error y ;

2021-11-08 18:28 UTC, AlfonsoScornavacca commented on controllers/applications.js
> +        if (error) { res.status(500) }
Falta el mensaje de error en varios res.status(500)

2021-11-09 02:29 UTC, AlfonsoScornavacca approved these changes

2021-11-09 02:38 UTC, AlfonsoScornavacca approved these changes

2021-11-09 15:26 UTC, davidcurras approved these changes

2021-11-09 16:19 UTC, merged