Ft sessions controller
davidcurras/mindset-2021 pull request #9
Opened 2021-11-08 13:09 UTC by AndresCespedes23

Development of getAll, getByID, getByName, add, edit and remove methods for candidates object.

2021-11-08 14:55 UTC, PabloMBernal requested changes

2021-11-08 14:55 UTC, PabloMBernal commented on controllers/sessions.js
> +  };
Hay problemas de indentacion

2021-11-08 14:55 UTC, PabloMBernal commented on controllers/sessions.js
> +        return;
este return podria estar en la linea anterior para que devuelva res.status

2021-11-09 01:05 UTC, PabloMBernal requested changes

2021-11-09 01:05 UTC, PabloMBernal commented on controllers/sessions.js
> +      return res.status(500).json({ message: 'Error deleting the session' });
aunque esto es mas simple, conviene que todos tengamos similar estructura de codigo al de julian, asi que pone el return en la siguiente linea

2021-11-09 02:06 UTC, PabloMBernal requested changes

2021-11-09 02:06 UTC, PabloMBernal commented on index.js
> +app.get('/session/byIdCandidate/:idCandidate', sessions.getByIdCandidate);
aca puede ir el id solo, total el parametro q eso identifica se gestiona internamente

2021-11-09 02:06 UTC, PabloMBernal commented on index.js
> -    html += '  <li>Candidates:';
esto tenias que dejarlo al igual que los campos de candidates

2021-11-09 02:54 UTC, PabloMBernal requested changes

2021-11-09 02:54 UTC, PabloMBernal commented on controllers/sessions.js
> +  const idCandidate = req.params.idCandidate;
creo que aca deberia ir solo id, ya que el parametro que le pasas por path es id

2021-11-09 03:04 UTC, PabloMBernal requested changes

2021-11-09 03:04 UTC, PabloMBernal commented on data/sessions.json
> +        {"id":2,"idPsychologists":2,"idCandidate":2,"date":"10/06/2021","time":"5:08 AM","isActive":true},
los elementos idPsychologists e idCandidate son secuenciales a lo largo del json y superan los valores maximos posibles de psicologos, esto se soluciona usando random(min,max) en mockaroo

2021-11-09 15:26 UTC, davidcurras approved these changes

2021-11-09 17:57 UTC, valeferaudo approved these changes

2021-11-09 18:22 UTC, PabloMBernal approved these changes

2021-11-09 18:38 UTC, merged